//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reactor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reactor.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamPackageDirectoryPath.
        /// </summary>
        public static string Config_StreamPackageDirectoryPath {
            get {
                return ResourceManager.GetString("Config_StreamPackageDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamServiceInstallationDirectoryPath.
        /// </summary>
        public static string Config_StreamServiceInstallationDirectoryPath {
            get {
                return ResourceManager.GetString("Config_StreamServiceInstallationDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactor Core Service. Responsible for managing services participating in the Reactor Services Platform..
        /// </summary>
        public static string Core_ServiceDescription {
            get {
                return ResourceManager.GetString("Core.ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service did not enter a running state within the alloted timeout period..
        /// </summary>
        public static string Error_ServiceStartTimedOut {
            get {
                return ResourceManager.GetString("Error_ServiceStartTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service did not enter a stopped state within the alloted timeout period..
        /// </summary>
        public static string Error_ServiceStopTimedOut {
            get {
                return ResourceManager.GetString("Error_ServiceStopTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates to AppConfig not yet supported by this instance.
        /// </summary>
        public static string Error_UpdatesToAppConfigNotYetSupportedByThisInstance {
            get {
                return ResourceManager.GetString("Error_UpdatesToAppConfigNotYetSupportedByThisInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to quit.
        /// </summary>
        public static string FatalExit_Press_any_key_to_quit {
            get {
                return ResourceManager.GetString("FatalExit_Press_any_key_to_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;exit&apos; to quit.
        /// </summary>
        public static string HostService_Run_Type__exit__to_quit {
            get {
                return ResourceManager.GetString("HostService_Run_Type__exit__to_quit", resourceCulture);
            }
        }
    }
}
